# NumPy Arrays

In [25]:
import numpy as np

In [26]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [27]:
Arr_10_0 = np.zeros(10)

In [28]:
print(Arr_10_0)
len(Arr_10_0)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


10

In [50]:
Arr_10_1 = np.ones(10)
print(Arr_10_1)
len(Arr_10_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


10

In [51]:
arr_5 = np.ones(10)
arr_5_10 =arr_5 * 5
print(arr_5_10)
len(arr_5_10)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


10

In [108]:
arr = np.arange(10,50)
print(arr)
print(len(arr))
arr.reshape(5,8)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
40


array([[10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [110]:
arr_3x3_0_8 = np.arange(0,9).reshape(3,3)

arr_3x3_0_8
#print('\n')
#arr_3x3_0_8.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
arr_Identity = np.eye(3)
arr_Identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
x = np.random.rand(1)
print(x)

[0.0079897]


In [76]:
X = np.random.randn(25)
X

array([-1.17415823, -0.19004224,  1.40445549,  0.34077865,  0.4437278 ,
        1.41818618, -0.06485927, -0.00674983, -1.46490601,  0.98493915,
        1.19001955,  0.61391022, -0.86142333,  0.64913383,  1.11554399,
        1.4113942 , -0.09200602, -0.56898798, -0.14174687,  0.17711766,
        1.73547999, -0.37039126, -0.50585084, -0.5051017 , -0.57375316])

In [112]:
Y = np.linspace(0.01,1,100)
Y
print(Y.reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [82]:
Y = np.linspace(0,1,20)
Y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [83]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [88]:
mat[3:4,4:]

array([[20]])

In [89]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [90]:
mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [91]:
mat[4:,0:]

array([[21, 22, 23, 24, 25]])

In [95]:

count = 0
for i in mat:
    count = count + i
print(count)
sum(count)

[55 60 65 70 75]


325

In [113]:
#mat.sum()    ......one way

#np.sum(mat)  ......another way

325

In [114]:
#standard for mat
np.std(mat)

7.211102550927978

In [119]:
#sum of column elements
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [106]:
count = 0
sum = 0
for i in mat:
    #count = count + i
    #print(count)
    for j in mat:
        sum = sum + j
    print(sum)

[55 60 65 70 75]
[110 120 130 140 150]
[165 180 195 210 225]
[220 240 260 280 300]
[275 300 325 350 375]


In [ ]:
np.sum()

In [125]:
import pandas as pd
import numpy as np

In [129]:
np.random.seed()
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:

Births = np.genfromtxt('Births.csv',delimiter = ',',filling_values = -1000 , skip_header = 1, dtype = 'float')

np.set_printoptions(suppress=True)

In [168]:
Births.size

35512

In [169]:
print(Births)
print('\n')
print("the shape of the given file is ......" , Births.shape)

[[ -1000. 100100.  -1000. ...     18.     18.     15.]
 [ -1000. 100200.  -1000. ...     33.     30.     24.]
 [ -1000. 100300.  -1000. ...      0.      0.      0.]
 ...
 [ -1000. 666673.  -1000. ...      0.      0.      0.]
 [ -1000. 999998.  -1000. ...      6.      9.      6.]
 [ -1000. 999999.  -1000. ...      0.      0.      0.]]


the shape of the given file is ...... (4439, 8)


In [179]:
birth2 = np.genfromtxt('Births.csv',delimiter = ',',filling_values = -1000 , skip_header = 1, dtype ='float' )
birth2[:5]

array([[ -1000., 100100.,  -1000.,     12.,     15.,     18.,     18.,
            15.],
       [ -1000., 100200.,  -1000.,     39.,     33.,     33.,     30.,
            24.],
       [ -1000., 100300.,  -1000.,      0.,      0.,      0.,      0.,
             0.],
       [ -1000., 100400.,  -1000.,     12.,     15.,      9.,      6.,
            12.],
       [ -1000., 100500.,  -1000.,     18.,      3.,     15.,      9.,
            18.]])

In [181]:
np.savetxt('birth2.csv', birth2, delimiter =',')
np.set_printoptions(suppress = True)

In [185]:
arr1 = np.zeros([4,4])

In [186]:
arr2 = np.ones([4,4])

In [189]:
print(arr1)
print('\n')
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [190]:
np.concatenate([arr1,arr2], axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [191]:
np.vstack([arr1,arr2],)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [194]:
np.r_[arr1,arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [195]:
np.c_[arr1,arr2]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [196]:
np.hstack([arr1,arr2])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [197]:
np.concatenate([arr1,arr2], axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [198]:
arr = np.random.randint(1,10, size=[10,5])

In [199]:
arr

array([[9, 9, 7, 3, 9],
       [8, 3, 2, 6, 5],
       [5, 6, 8, 4, 7],
       [5, 4, 8, 7, 2],
       [4, 6, 9, 5, 7],
       [4, 3, 1, 5, 3],
       [5, 2, 8, 9, 3],
       [9, 8, 2, 7, 9],
       [6, 4, 1, 1, 3],
       [9, 9, 3, 7, 6]])

In [219]:
Sorted_Index = arr[:,1].argsort()

In [220]:
arr[Sorted_Index]

array([[5, 2, 8, 9, 3],
       [8, 3, 2, 6, 5],
       [4, 3, 1, 5, 3],
       [5, 4, 8, 7, 2],
       [6, 4, 1, 1, 3],
       [5, 6, 8, 4, 7],
       [4, 6, 9, 5, 7],
       [9, 8, 2, 7, 9],
       [9, 9, 7, 3, 9],
       [9, 9, 3, 7, 6]])